name: <%= project.lower %>_mobile
description: <%= project.lower %> mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
<% if (typeof dartDeps !== 'undefined') { var dartKeys = Object.keys(dartDeps); for (var i = 0; i < dartKeys.length; i++) { %>
<% if (dartDeps[dartKeys[i]] === 'sdk') { %>
  <%= dartKeys[i] %>:
    sdk: flutter
<% } else { %>
  <%= dartKeys[i] %>: <%= dartDeps[dartKeys[i]] %>
<% } %>
<% } } %>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
